const UserPageActionTypes = {
  GET_USER_START: 'userPage/GET_USER_START',
  GET_USER_SUCCESS: 'userPage/GET_USER_SUCCESS',
  GET_USER_FAILURE: 'userPage/GET_USER_FAILURE',
  REFRESH_PAGE: 'userPage/REFRESH_PAGE',
  TOGGLE_AVATAR_MODAL_SHOWN: 'userPage/TOGGLE_AVATAR_MODAL_SHOWN',
  ADD_TO_FRIENDS: 'userPage/ADD_TO_FRIENDS',
};

export default UserPageActionTypes;
