const FriendsActionTypes = {
  GET_FRIENDS_START: 'friends/GET_FRIENDS_START',
  GET_FRIENDS_SUCCESS: 'friends/GET_FRIENDS_SUCCESS',
  GET_FRIENDS_FAILURE: 'friends/GET_FRIENDS_FAILURE',
  GET_FRIEND_REQUESTS_START: 'friends/GET_FRIEND_REQUESTS_START',
  GET_FRIEND_REQUESTS_SUCCESS: 'friends/GET_FRIEND_REQUESTS_SUCCESS',
  GET_FRIEND_REQUESTS_FAILURE: 'friends/GET_FRIEND_REQUESTS_FAILURE',
  GET_SUBSCRIPTIONS_START: 'friends/GET_SUBSCRIPTIONS_START',
  GET_SUBSCRIPTIONS_SUCCESS: 'friends/GET_SUBSCRIPTIONS_SUCCESS',
  GET_SUBSCRIPTIONS_FAILURE: 'friends/GET_SUBSCRIPTIONS_FAILURE',
};

export default FriendsActionTypes;
