const SocialsActionTypes = {
  GET_FRIENDS_START: 'socials/GET_FRIENDS_START',
  GET_FRIENDS_SUCCESS: 'socials/GET_FRIENDS_SUCCESS',
  GET_FRIENDS_FAILURE: 'socials/GET_FRIENDS_FAILURE',
  GET_FRIEND_REQUESTS_START: 'socials/GET_FRIEND_REQUESTS_START',
  GET_FRIEND_REQUESTS_SUCCESS: 'socials/GET_FRIEND_REQUESTS_SUCCESS',
  GET_FRIEND_REQUESTS_FAILURE: 'socials/GET_FRIEND_REQUESTS_FAILURE',
  GET_SUBSCRIPTIONS_START: 'socials/GET_SUBSCRIPTIONS_START',
  GET_SUBSCRIPTIONS_SUCCESS: 'socials/GET_SUBSCRIPTIONS_SUCCESS',
  GET_SUBSCRIPTIONS_FAILURE: 'socials/GET_SUBSCRIPTIONS_FAILURE',
  SHOW_FRIENDS: 'socials/SHOW_FRIENDS',
  SHOW_FRIEND_REQUESTS: 'socials/SHOW_FRIEND_REQUESTS',
  SHOW_SUBSCRIPTIONS: 'socials/SHOW_SUBSCRIPTIONS',
  REMOVE_FRIEND_REQUEST: 'socials/REMOVE_FRIEND_REQUEST',
  REMOVE_FRIEND: 'socials/REMOVE_FRIEND',
};

export default SocialsActionTypes;
