export const GET_FRIENDS_STATES = {
  FETCHING: 'GET_FRIENDS/FETCHING',
  SUCCESS: 'GET_FRIENDS/SUCCESS',
  FAILURE: 'GET_FRIENDS/FAILURE',
};

export const GET_FRIEND_REQUESTS_STATES = {
  FETCHING: 'GET_FRIEND_REQUESTS/FETCHING',
  SUCCESS: 'GET_FRIEND_REQUESTS/SUCCESS',
  FAILURE: 'GET_FRIEND_REQUESTS/FAILURE',
};

export const GET_SUBSCRIPTIONS_STATES = {
  FETCHING: 'GET_SUBSCRIPTIONS/FETCHING',
  SUCCESS: 'GET_SUBSCRIPTIONS/SUCCESS',
  FAILURE: 'GET_SUBSCRIPTIONS/FAILURE',
};

export const SOCIAL_PAGE_STATES = {
  SHOW_FRIENDS: 'SOCIAL_PAGE/SHOW_FRIENDS',
  SHOW_FRIEND_REQUESTS: 'SOCIAL_PAGE/SHOW_FRIEND_REQUESTS',
  SHOW_SUBSCRIPTIONS: 'SOCIAL_PAGE/SHOW_SUBSCRIPTIONS',
};
