export const GET_USER_STATES = {
  FETCHING: 'GET_USER/FETCHING',
  SUCCESS: 'GET_USER/SUCCESS',
  FAILURE: 'GET_USER/FAILURE',
};

export const SIGN_UP_STATES = {
  FETCHING: 'SIGN_UP/FETCHING',
  SUCCESS: 'SIGN_UP/SUCCESS',
  FAILURE: 'SIGN_UP/FAILURE',
};

export const SIGN_IN_STATES = {
  FETCHING: 'SIGN_IN/FETCHING',
  SUCCESS: 'SIGN_IN/SUCCESS',
  FAILURE: 'SIGN_IN/FAILURE',
};

export const CHANGE_USER_STATES = {
  FETCHING: 'CHANGE_USER/FETCHING',
  SUCCESS: 'CHANGE_USER/SUCCESS',
  FAILURE: 'CHANGE_USER/FAILURE',
};

export const MANAGE_FRIENDS_STATES = {
  FETCHING: 'ADD_TO_FRIENDS/FECHING',
  SUCCESS: 'ADD_TO_FRIENDS/SUCCESS',
  FAILURE: 'ADD_TO_FRIENDS/FAILURE',
};
